leg:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500

  # Trajectory Controllers ---------------------------------------
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - Revolute_3
      - Revolute_4
      - Revolute_5
    gains:
      Revolute_3: {p: 500.0, d: 0.0, i: 0.0, i_clamp: 0.0}
      Revolute_4: {p: 500.0, d: 0.0, i: 0.0, i_clamp: 0.0}
      Revolute_5: {p: 500.0, d: 0.0, i: 0.0, i_clamp: 0.0}